### ISSUE TITLE
Il controllo di sicurezza non corrisponde. La richiesta è stata interrotta per prevenire qualsiasi violazione di sicurezza. Riprova.

### ISSUE THREAD

**Issue by Mozartino74** [retepasw/joomla-spid#12]
### Steps to reproduce the issue

Cliccare sull'icona ENTRA CON SPID-->selezione identity provider

### Expected result

Richiesta credenziali identity provider

### Actual result

Messaggio: 
Attenzione
Il controllo di sicurezza non corrisponde. La richiesta è stata interrotta per prevenire qualsiasi violazione di sicurezza. Riprova.
![attenzione](https://user-images.githubusercontent.com/35662623/35222464-4b8e6ad6-ff7e-11e7-8e2b-c201c0bad7e5.JPG)

### System information (as much as possible)

Google Chrome, Joomla! 3.8.3

### Additional comments

Procedura amministrativa non ancora completata.
![cache](https://user-images.githubusercontent.com/35662623/35222590-b5947ee8-ff7e-11e7-80fe-31394b1e75db.JPG)

**Comment by atodaro** [comment]
@Mozartino74 sarebbe necessario avere qualche informazione aggiuntiva, come ad esempio da quanti giorni è stata ricevuta la risposta al ticket di invio del metadato. Il tipo di problema che segnali si verifica quando l'autorizzazione ricevuta da agid non è stata propagata ancora agli IdP. 
Ricordo, inoltre, che questo generi di problemi possono essere segnalati più opportunamente sul forum gestito da agid e developers italia, disponibile al seguente link:
https://forum.italia.it/c/spid

P.S.: ho appena verificato sul sito del tuo istituto che Poste ID consente l'accesso (troverai nel backend la richiesta di accesso che puoi annullare) e che il componente si collega anche agli altri IdP
![screenshot-www comprensivomontemurlo gov it-2018-01-22-15-06-06-888](https://user-images.githubusercontent.com/12257435/35224637-f3e8b856-ff85-11e7-9b52-0d697b457bb5.png)

**Comment by Mozartino74** [comment]
@atodaro grazie per la risposta.
Sto cercando di circoscrivere il problema e se dal pannello di configurazione globale-->Sistema-->Impostazioni cache-->Cache di sistema--> seleziono NO - Cache disabilitata non visualizzo più il messaggio di errore.
Sul vostro sito scolastico che impostazioni avete?

Grazie e buona serata.

**Comment by atodaro** [comment]
Stesso tipo di configurazione

**Comment by Mozartino74** [comment]
Grazie.
Io praticamente nelle impostazioni avevo selezionasi SI Cache unica moderata...
