### ISSUE TITLE
SPID e Area Riservata

### ISSUE THREAD

**Issue by Mozartino74** [retepasw/joomla-spid#13]
### Steps to reproduce the issue
Accesso a SPID 

### Expected result
Entrare nell'area riservata del sito.

### Actual result
Si viene reinderizzati sulla home page

### Additional comments
Joomla! 3.8.3

**Comment by eshiol** [comment]
Con l'aggiornamento 3.8.1 è possibile selezionare o creare la pagina alla quale reindirizzare gli utenti dopo l'accesso all'area riservata. Di default rimane nella stessa pagina.
![image](https://user-images.githubusercontent.com/12718836/35397510-fb2c64b6-01ef-11e8-8de1-825e3b233325.png)

**Comment by Mozartino74** [comment]
Prima di tutto grazie per la risposta.
Ho specificato la destinazione dell'articolo relativo all'area riservata ma il risultato è quello di essere reinderizzato all'home page del sito con l'area riservata abilitata mentre pensavo di ritrovarmi direttamente nella pagina dedicata.

A distanza di qualche giorno non ritrovo più quell'opzione per eventualmente cambiare destinazione.

**Comment by eshiol** [comment]
Il modulo fa proprio quello che dici. Specifica meglio la configurazione del modulo e della voce di menu di area riservata che utilizzi, così proviamo a verificare se si tratta di un bug.

**Comment by Mozartino74** [comment]
Non ricordo quando ho specificato come articolo quello dell'area riservata perché dopo aver installato il componente qualche giorno dopo c'è stato qualche aggiornamento.
Adesso nel modulo non ritrovo più tale opzione.
Per quanto riguarda la voce di menu queste sono le opzioni:
![schermata area riservata](https://user-images.githubusercontent.com/35662623/35429102-d79ae490-0272-11e8-8858-c46288801af3.png)

Nel campo Redirezionamento dopo accesso ho messo il link alla pagina riservata.
Buona giornata

**Comment by Mozartino74** [comment]
Con la scuola abbiamo avviato la procedura amministrativa.
Per verificare la problematica di cui sopra pensavo di disinstallere il componente e rimettere la versione precedente: potrebbe causare problemi alla procedura in essere?

**Comment by Mozartino74** [comment]
Salve. 
Ho appena aggiornato il modulo SPID LOGIN alla versione 3.8.2 e il reindrizzamento funziona correttamente.
Grazie!
