### ISSUE TITLE
Update e rendrizzamento errato

### ISSUE THREAD

**Issue by Mozartino74** [retepasw/joomla-spid#20]
### Steps to reproduce the issue

Ho appena effettuato gli aggiornamenti proposti per il componente SPID (modulo e plugin)
Sul sito comprensivomontemurlo.gov.it clicco su ENTRA CON SPID

### Expected result

Reindrizzamento verso il provider selezionato

### Actual result

Si viene reindrizzati alla pagina indicata nel modulo SPID LOGIN Redirezionamento dopo accesso
(https://www.comprensivomontemurlo.gov.it/area-riservata.html)

### System information (as much as possible)

Joomla! 3.8.5

**Comment by eshiol** [comment]
Puoi indicare quale aggiornamento ha generato il problema?

**Comment by Mozartino74** [comment]
Oggi, se non erro, ho aggiornato sia il modulo sia il plugin SPID LOGIN sia il plugin Authentication - SPiD

**Comment by eshiol** [comment]
prova a fare un downgrade e verifica cosa ha mandato in tilt SPiD

**Comment by Mozartino74** [comment]
Devo installare la versione precedente dei moduli/plugin?
Potresti cortesemente indicarmi quali devo scaricare?
Grazie anticipatamente

**Comment by Mozartino74** [comment]
Il problema sembra essere il plugin...
Ho installato Authentication - SPiD 3.8.1.111 e adesso i provider rispondono correttamente...

Attendo osservazioni in merito.

**Comment by eshiol** [comment]
Grazie della segnalazione, ho provveduto a bloccare l'aggiornamento incriminato in attesa di capire il motivo del problema.

**Comment by eshiol** [comment]
Il problema non è presente con la seguente configurazione
Module SPiD Login 3.8.3
Plugin Authentication - SPiD 3.8.1.111
Plugin User - SPiD 3.8.1

**Comment by Mozartino74** [comment]
Esatto.

**Comment by eshiol** [comment]
PR #24 risolve il problema
