### ISSUE TITLE
Autenticazione tramite OTP (One-Time Password)

### ISSUE THREAD

**Issue by Mozartino74** [retepasw/joomla-spid#23]
### Steps to reproduce the issue

Entra con Spid-->Seleziona provider-->Inserisci le credenziali

### Expected result

Autenticazione tramite OTP (One-Time Password)

### Actual result

Si accede direttamente alla pagina riservata.

### System information (as much as possible)

Joomla! 3.8.5

### Additional comments

Richiesta di verifica attivata ma ancora non completata a causa dell'elevato numero di richieste e del non trascurabile quantitativo di tempo necessario per effettuare una singola verifica.

**Comment by eshiol** [comment]
Immagino tu stia parlando di SpidL2. La funzionalità non è ancora disponibile. Lo sarà a breve in via sperimentale.
