### ISSUE TITLE
Immagine Login SPID

### ISSUE THREAD

**Issue by Mozartino74** [retepasw/joomla-spid#9]
### Steps to reproduce the issue
Ho installato il componente pkg_spid-3.8.0.17.zip

### Expected result
Icona LOGIN SPID blu

### Actual result
Icona Login SPID bianca/trasparente

### System information (as much as possible)
Joomla! 3.8.3 Template Joomla!Fap Pro

### Additional comments
![entra con spid](https://user-images.githubusercontent.com/35662623/35196237-a761e3ce-fecf-11e7-854a-428c5bcac819.JPG)

**Comment by atodaro** [comment]
@Mozartino74 nel template Fap free, pur inserendo un codice per consentire la corretta visualizzazione del banner nel campo "additional css", non abbiamo avuto il comportamento che ci si attendeva. Considerato che utilizzi la versione "premium" dovresti rivolgerti direttamente allo sviluppatore.

**Comment by eshiol** [comment]
questo è il css da inserire
```
.button-spid {
	background-color: #06C!important;
	color: #FFF!important;
}
```

**Comment by Mozartino74** [comment]
Grazie.
In quale file css devo apportare la modifica?

**Comment by atodaro** [comment]
Se hai la versione Pro verifica se, dopo aver inserito il codice nel campo "additional css", la modifica viene letta.

**Comment by Mozartino74** [comment]
Non era necessario create un file CSS. 
Con il template Joomla! Fap bastava incollare il codice sopra nella configurazione del template -> stili personalizzati -> regole css aggiuntive.
